In [187]:
import re
import time
from gensim import corpora
from gensim.models import Word2Vec
from datetime import datetime
import os
import glob
import numpy as np
from scipy.stats import pearsonr
from skbio.stats.distance import mantel
from skbio.stats.distance import DistanceMatrix

## MODEL CREATION
This is a test are for model creation, the final code is in w2v_batch.py and run_w2v_00.sh

#### Sentences and Models

In [4]:
#
# parses a dicorpus file to build up sentences to create a model
#
def get_corpus_sentences(corpus_file):
    # initialise
    s = time.time()
    sentences = []
    counter = 0
    num_tokens = 0
    print(f'Parsing file for sentences: {corpus_file}')
    with open(corpus_file, 'r') as file:
        for line in file:
            line = line.strip('\n')
            tokens = line.split()
            sentences.append(tokens)
            counter +=1
            num_tokens += len(tokens)
    # time check
    e = time.time()
    print(f"{counter} sentences processed, {num_tokens} added in {e - s}s" )
    return sentences

In [5]:
#
# Create W2V model
#
def create_w2v(sentences, model_name, vector_size, window_size, mc):
    current_date    = datetime.now().strftime('%Y%m%d')
    model_name      = model_name + ".model"
    
    s = time.time()
    
    # create model from sentences       
    w2v = Word2Vec(sentences, vector_size=vector_size, window=window_size, workers=4, epochs=10, min_count=mc)
    
    # time check
    e = time.time()
    print(f"{model_name} | {vector_size} | {window_size} | {mc} | {round(e-s,2)}s")
          
    # save model      
    w2v.save(model_name)

#### Execution

In [5]:
##corpus_file     = "/Users/patrick/dev/ucl/comp0158_mscproject/data/corpus/uniref100_e_corpus_20240810.txt"
#sentences       = get_corpus_sentences(corpus_file)

In [6]:
# CONFIGURATION
model_dir       = "/Users/patrick/dev/ucl/comp0158_mscproject/data/models/"
current_date    = datetime.now().strftime('%Y%m%d')

# create models
'''
for vector_size in range(5, 10, 5):
    for window_size in range(5,10, 5):
        # create model
        model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)
        create_w2v(sentences, model_name, vector_size, window )
'''

'''
corpus_file     = "/Users/patrick/dev/ucl/comp0158_mscproject/data/corpus/uniref100_e_corpus_20240810.txt"
sentences       = get_corpus_sentences(corpus_file)

vector_size = 5
window_size = 5
min_count   = 3
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )

vector_size = 10
window_size = 5
min_count   = 3
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )

vector_size = 5
window_size = 5
min_count   = 5
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )

vector_size = 10
window_size = 5
min_count   = 5
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )


vector_size = 20
window_size = 5
min_count   = 3
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )


vector_size = 20
window_size = 5
min_count   = 5
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )



vector_size = 5
window_size = 10
min_count   = 3
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )

vector_size = 10
window_size = 10
min_count   = 3
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )

vector_size = 20
window_size = 10
min_count   = 3
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )

vector_size = 5
window_size = 10
min_count   = 5
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )

vector_size = 10
window_size = 10
min_count   = 5
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )

vector_size = 20
window_size = 10
min_count   = 5
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )

'''

corpus_file     = "/Users/patrick/dev/ucl/comp0158_mscproject/data/corpus/uniref100_e_corpus_20240810.txt"
sentences       = get_corpus_sentences(corpus_file)

vector_size = 5
window_size = 5
min_count   = 1
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )

vector_size = 10
window_size = 5
min_count   = 1
model_name = model_dir+"w2v_"+current_date + "_v"+str(vector_size)+"_w"+str(window_size)+"_mc"+str(min_count)
create_w2v(sentences, model_name, vector_size, window_size, min_count )

Parsing file for sentences: /Users/patrick/dev/ucl/comp0158_mscproject/data/corpus/uniref100_e_corpus_20240810.txt
45909435 sentences processed, 255674676 added in 558.3428671360016s
/Users/patrick/dev/ucl/comp0158_mscproject/data/models/w2v_20240814_v5_w5_mc1.model | 5 | 5 | 1 | 1474.09s
/Users/patrick/dev/ucl/comp0158_mscproject/data/models/w2v_20240814_v10_w5_mc1.model | 10 | 5 | 1 | 1362.54s


#### Extract vocab

In [16]:
def write_vocab(model_dir, model_name, vocab_dir):
    
    base_name_search  = re.search("(w2v_.*)\.model", model_name)
    base_name         = base_name_search.group(1)

    vocab_file  = vocab_dir+base_name+'_vocab.txt'
    model       = Word2Vec.load(model_dir+model_name)
    
    print(f"Extracting vocab for model {base_name} to {vocab_file}.")

    of = open(vocab_file, "w")
    for word in model.wv.key_to_index:
        of.write(word + '\n')
    of.close()

# set directories
vocab_dir="/Users/patrick/dev/ucl/comp0158_mscproject/data/models/vocab/"
model_dir="/Users/patrick/dev/ucl/comp0158_mscproject/data/models/"

# get vocab for a particular file
#model_name = "w2v_20240811_v5_w5_mc3.model"
#write_vocab(model_dir, model_name, vocab_dir)

# find all model files
file_list = glob.glob(os.path.join(model_dir, '*.model'))
for file_path in file_list:
    model_name_s  = re.search("(w2v_.*)\.model", file_path)
    model_name         = model_name_s.group(1)
    
    print(f"Getting vocab for {model_name}")
    #write_vocab(model_dir, model_name, vocab_dir)


Getting vocab for w2v_20240811_v5_w10_mc5
Getting vocab for w2v_20240811_v5_w10_mc3
Getting vocab for w2v_20240811_v10_w5_mc3
Getting vocab for w2v_20240811_v10_w10_mc5
Getting vocab for w2v_20240811_v5_w5_mc5
Getting vocab for w2v_20240811_v20_w5_mc5
Getting vocab for w2v_20240811_v5_w5_mc3
Getting vocab for w2v_20240811_v10_w10_mc3
Getting vocab for w2v_20240811_v10_w5_mc5
Getting vocab for w2v_20240811_v20_w5_mc3
Getting vocab for w2v_20240811_v20_w10_mc5
Getting vocab for w2v_20240811_v20_w10_mc3


<>:3: SyntaxWarning: invalid escape sequence '\.'
<>:26: SyntaxWarning: invalid escape sequence '\.'
<>:3: SyntaxWarning: invalid escape sequence '\.'
<>:26: SyntaxWarning: invalid escape sequence '\.'
/var/folders/kp/bqnb4b7n4ng50xtbznpbx7xh0000gn/T/ipykernel_90630/1526553224.py:3: SyntaxWarning: invalid escape sequence '\.'
  base_name_search  = re.search("(w2v_.*)\.model", model_name)
/var/folders/kp/bqnb4b7n4ng50xtbznpbx7xh0000gn/T/ipykernel_90630/1526553224.py:26: SyntaxWarning: invalid escape sequence '\.'
  model_name_s  = re.search("(w2v_.*)\.model", file_path)


In [ ]:
# get vocab for one model
vocab_dir="/Users/patrick/dev/ucl/comp0158_mscproject/data/models/vocab/"
model_dir="/Users/patrick/dev/ucl/comp0158_mscproject/data/models/"

# get vocab for a particular file
#model_name = "w2v_20240811_v5_w5_mc3.model"
#write_vocab(model_dir, model_name, vocab_dir)

In [18]:
# get vocab for all models
vocab_dir="/Users/patrick/dev/ucl/comp0158_mscproject/data/models/vocab/"
model_dir="/Users/patrick/dev/ucl/comp0158_mscproject/data/models/"

file_list = glob.glob(os.path.join(model_dir, '*.model'))
for file_path in file_list:
    model_name_s  = re.search("(w2v_.*\.model)", file_path)
    model_name         = model_name_s.group(1)
    write_vocab(model_dir, model_name, vocab_dir)

<>:7: SyntaxWarning: invalid escape sequence '\.'
<>:7: SyntaxWarning: invalid escape sequence '\.'
/var/folders/kp/bqnb4b7n4ng50xtbznpbx7xh0000gn/T/ipykernel_90630/122697594.py:7: SyntaxWarning: invalid escape sequence '\.'
  model_name_s  = re.search("(w2v_.*\.model)", file_path)


Extracting vocab for model w2v_20240811_v5_w10_mc5 to /Users/patrick/dev/ucl/comp0158_mscproject/data/models/vocab/w2v_20240811_v5_w10_mc5_vocab.txt.
Extracting vocab for model w2v_20240811_v5_w10_mc3 to /Users/patrick/dev/ucl/comp0158_mscproject/data/models/vocab/w2v_20240811_v5_w10_mc3_vocab.txt.
Extracting vocab for model w2v_20240811_v10_w5_mc3 to /Users/patrick/dev/ucl/comp0158_mscproject/data/models/vocab/w2v_20240811_v10_w5_mc3_vocab.txt.
Extracting vocab for model w2v_20240811_v10_w10_mc5 to /Users/patrick/dev/ucl/comp0158_mscproject/data/models/vocab/w2v_20240811_v10_w10_mc5_vocab.txt.
Extracting vocab for model w2v_20240811_v5_w5_mc5 to /Users/patrick/dev/ucl/comp0158_mscproject/data/models/vocab/w2v_20240811_v5_w5_mc5_vocab.txt.
Extracting vocab for model w2v_20240811_v20_w5_mc5 to /Users/patrick/dev/ucl/comp0158_mscproject/data/models/vocab/w2v_20240811_v20_w5_mc5_vocab.txt.
Extracting vocab for model w2v_20240811_v5_w5_mc3 to /Users/patrick/dev/ucl/comp0158_mscproject/data

### Test Area for model creation

In [14]:
# check if a pfam entry is in a model
model = Word2Vec.load("/Users/patrick/dev/ucl/word2vec/comp_0158_msc_project/data/models/hpc/mac/w2v_20240831_sg1_mc1_w3_v5_mac.model")

#pfam_id = 'PF19687'        # present in w2v_20240810_v5_w2.model
#pfam_id = 'PF01257'        # not present in w2v_20240810_v5_w2.model - but shouldn't be
#pfam_id = 'PF00424'        # not present in model - why not - only appears once in corpus
pfam_id = 'PF14033'        # present in w2v_20240810_v5_w2.model
pfam_id = 'PF00469'         # not present in model - why not - only appears once in corpus
pfam_id = 'PF03945'

try:
    print(model.wv[pfam_id])
except Exception as e:
    print(e)

[ 0.68811744 -0.7162888   1.8892967   0.36172312 -1.4784527 ]


## DISTANCES

#### Test Symmetric Matrices

In [61]:
matrix = np.array([[0, 2, 3, 4, 5],
                   [0, 0, 6, 7, 8],
                   [0, 0, 0, 9, 10],
                   [0, 0, 0, 0, 12],
                   [0, 0, 0, 0, 0]])

# Make the matrix symmetric
symmetric_matrix = matrix + matrix.T - np.diag(matrix.diagonal())

print('original matrix:\n', matrix, '\n')
print('symmetric matrix:\n', symmetric_matrix, '\n')

num_entries = matrix.shape[1]

for i in range(num_entries):
    for j in range(num_entries):
        try:
            assert (symmetric_matrix[i,j] == symmetric_matrix[j,i]), "matrix not symmetric"
        except AssertionError as e:
            print(f"Assertion failed: {e} i: {i} j: {j} :: {symmetric_matrix[i,j]} != {symmetric_matrix[j,i]}")

# break something
symmetric_matrix[1,3] = 11

for i in range(num_entries):
    for j in range(num_entries):
        try:
            assert (symmetric_matrix[i,j] == symmetric_matrix[j,i]), "matrix not symmetric"
        except AssertionError as e:
            print(f"Assertion failed: {e} i: {i} j: {j} :: {symmetric_matrix[i,j]} != {symmetric_matrix[j,i]}")

original matrix:
 [[ 0  2  3  4  5]
 [ 0  0  6  7  8]
 [ 0  0  0  9 10]
 [ 0  0  0  0 12]
 [ 0  0  0  0  0]] 

symmetric matrix:
 [[ 0  2  3  4  5]
 [ 2  0  6  7  8]
 [ 3  6  0  9 10]
 [ 4  7  9  0 12]
 [ 5  8 10 12  0]] 

Assertion failed: matrix not symmetric i: 1 j: 3 :: 11 != 7
Assertion failed: matrix not symmetric i: 3 j: 1 :: 7 != 11


### Test reduce and reorder python matrix

In [160]:

# ------ See verision in utilities sectoin which works with numpy vectors


# Reduces the target matrix to only have entries that are common to 
# 2 vectors list the entries in 2 matrices. This routine identified the 
# common elements between these vectors and removes them from the target matrix
# It also reorders the target matrix so that the entries are in the same order

# source_vector : list of items in the source matrix
# target_vector : list of items in the target matrix
# target_matrix : the matrix to be reduced and reordered

def reduce_python_matrix(source_vector, target_vector, target_matrix):

    reorder_indices = []
    # get index of each source vector in the target vector and add that index to a list
    # thus this list is now in the same order as the source vector
    for item in source_vector:
        if (item == 'GAP' or item == 'START_GAP' or item == 'STOP_GAP' or item == 'DISORDER'):
            continue
        else:
            index = np.where(target_vector == item)[0]
            reorder_indices.append(index[0])
    
    reordered_vector = target_vector[reorder_indices]

    print('target indices for items only in the source vector:', reorder_indices, '(should only have these rows and columns left).\n')
    print('target entries for items only in the source vector:', target_vector[reorder_indices], '\n')

    # take ony the rows from the target - but this will still have all columns
    reordered_matrix = target_matrix[reorder_indices, :]
    # now take only the columns
    reordered_matrix = reordered_matrix[:, reorder_indices]

    return reordered_vector, reordered_matrix

# ------------------------------------------------------------------------

source_vector = np.array(['d', 'b'])
target_vector = np.array(['a', 'b', 'c', 'd'])

print(f"source vector: {source_vector}\ntarget vector: {target_vector}\n")
print(f"original target matrix: \n{target_matrix}\n")

target_matrix = np.array([  [10, 11, 12, 13],
                            [20, 21, 22, 23],
                            [30, 31, 32, 33],
                            [40, 41, 42, 43]])


reduced_target_vector, reduced_target_matrix = reduce_python_matrix(source_vector, target_vector, target_matrix)

print('------------------- result -----------------\n')
print(f"reduced target vector: \n{reduced_target_vector}")
print(f"reduced target matrix: \n{reduced_target_matrix}")



source vector: ['d' 'b']
target vector: ['a' 'b' 'c' 'd']

original target matrix: 
[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]

target indices for items only in the source vector: [3, 1] (should only have these rows and columns left).

target entries for items only in the source vector: ['d' 'b'] 

------------------- result -----------------

reduced target vector: 
['d' 'b']
reduced target matrix: 
[[43 41]
 [23 21]]


In [ ]:
'''
# Reduces and reorders a target matrix so that it only has the items in source_v
#
# - DOES NOT ASSUME THAT ALL ITEMS IN SOURCE ARE IN TARGET
#
# source_v : list of items we want to have and in the order we need them
# target_v : items that are currently in a target_matrix and the order they are in (assume same ordering rows and columns)
# target_matrix : the matrix we want to remove ros/columns from and reorder to the same order as source_v
# returns a new matrix which is the original target matrix but modified as decribed
def reorder_matrix_2(source_v, target_v, source_matrix, target_matrix):

    target_indices  = []
    source_indices  = []
    for i, item in enumerate (source_v):
        if(item.startswith("PF")):
            target_index = np.where(target_v == item)[0]
            #print(f"target index for {item}: {target_index}")
            # if the source is in the target
            if(target_index.size !=0):
                target_indices.append(target_index[0])
                source_indices.append(i)
        else:
            continue

    #print('indices needed in target matrix and in new order', target_indices)
    #print('indices needed in source vector', source_indices)

    # reorder the matrix
    reordered_t_matrix = target_matrix[target_indices, :]
    reordered_t_matrix = reordered_t_matrix[:, target_indices]
    
    reordered_s_matrix = source_matrix[source_indices, :]
    reordered_s_matrix = reordered_s_matrix[:, source_indices]
    
    reduced_source_v  = source_v[source_indices]
    
    return reordered_s_matrix, reordered_t_matrix



source_vector = np.array(['d', 'b'])
target_vector = np.array(['a', 'b', 'c', 'd'])

target_matrix = np.array([  [10, 11, 12, 13],
                            [20, 21, 22, 23],
                            [30, 31, 32, 33],
                            [40, 41, 42, 43]])

reduced_source_matrix, reduced_target_matrix = reorder_matrix_2(source_vector, target_vector, target_matrix)

print(f"source vector: {source_vector}\ntarget vector: {target_vector}\n")
print(f"original target matrix: \n{target_matrix}\n")

print(f"reduced source matrix: \n{reduced_source_matrix}")
print(f"reduced target matrix: \n{reduced_target_matrix}")
'''

## DISTANCE UTILITIES - FINAL

In [176]:

#
# get index of a pfam entry from the vector so we can look it up
#
def get_word_index(word, vocab_vector):
    for i in range (len(vocab_vector)):
        if vocab_vector[i] == word:
            #print(f"match for {word} at index {i}")
            return i

# ------------------- SYMMETRIC MATRICES ----------------------------

#
# make a matrix symmetrical - my word2vec matrices are not
#
def make_symmetrical(matrix):
    matrix_sym = matrix + matrix.T - np.diag(matrix.diagonal())
    return matrix_sym

#
# test a matrix to see if its symmetric
#
def test_symmetric(symmetric_matrix):
    print(symmetric_matrix.shape)
    num_entries = symmetric_matrix.shape[1]
    for i in range(num_entries):
        for j in range(num_entries):
            try:
                assert (symmetric_matrix[i,j] == symmetric_matrix[j,i]), "matrix not symmetric"
            except AssertionError as e:
                print(f"Assertion failed: {e} i: {i} j: {j} :: {symmetric_matrix[i,j]} != {symmetric_matrix[j,i]}")



# ------------------- GET MATRICES AND VECTORS FROM NPY FILE ----------------------------

#
# extract vocab vector and matrix from npy file
#                
def extract_matrix_vector_files(npy_file_name):
    npy_f              = open(npy_file_name, 'rb')
    dist_matrix         = np.load(npy_f) #loads first array
    vocab_vector        = np.load(npy_f)
    
    return vocab_vector, dist_matrix



# ------------------- GET PFAM IDS FROM EVO VECTOR ----------------------------

#
# vectors in evo matrix have format K1SVA3.1/50-86|PF02829
# need to extract these
#
def extract_evo_pfam_ids(evo_vector):
    pfam_ids = []
    for item in evo_vector:
        #print(f"searching in {item}")
        pfam_search  = re.search("\|(PF.*)", item)
        pfam_id       = pfam_search.group(1)
        #print(f"found {pfam_id}")
        pfam_ids.append(pfam_id)
    return pfam_ids

    

# ------------- REDUCE A MATRIX BASED UPON COMMON ENTRIES IN A VECTOR ----------

# Reduces the target matrix to only have entries that are common to 
# 2 vectors list the entries in 2 matrices. This routine identified the 
# common elements between these vectors and removes them from the target matrix
# It also reorders the target matrix so that the entries are in the same order

# source_vector : list of items in the source matrix
# target_vector : list of items in the target matrix
# target_matrix : the matrix to be reduced and reordered

def reduce_matrix(source_vector, target_vector, target_matrix):

    reorder_indices = []
    missing_items   = []
    found_items     = []
    # get index of each source vector in the target vector and add that index to a list
    # thus this list is now in the same order as the source vector
    for item in source_vector:
        if (item == 'GAP' or item == 'START_GAP' or item == 'STOP_GAP' or item == 'DISORDER'):
            continue
        else:
            try:
                find_index = np.where(target_vector == item)[0]
                if len(find_index) > 0 :
                    reorder_indices.append(find_index[0])
                    found_items.append(item)
                    #print('found item at', find_index[0])
                else:
                    #print(item, 'not found in target vector')
                    missing_items.append(item)
            except Exception as e:
                print(f"error looping through vector at {item}, {e}")
    
    reordered_vector = target_vector[reorder_indices]

    #print('target indices for items only in the source vector:', reorder_indices, '(should only have these rows and columns left).\n')
    #print('target entries for items only in the source vector:', target_vector[reorder_indices], '\n')

    # take ony the rows from the target - but this will still have all columns
    reordered_matrix = target_matrix[reorder_indices, :]
    # now take only the columns
    reordered_matrix = reordered_matrix[:, reorder_indices]

    return found_items, missing_items, reordered_vector, reordered_matrix




# ------------------------------------------------------------------------



'''
# Reduces and reorders a target matrix so that it only has the items in source_v
#
# - DOES NOT ASSUME THAT ALL ITEMS IN SOURCE ARE IN TARGET
#
# source_v : list of items we want to have and in the order we need them
# target_v : items that are currently in a target_matrix and the order they are in (assume same ordering rows and columns)
# target_matrix : the matrix we want to remove ros/columns from and reorder to the same order as source_v
# returns a new matrix which is the original target matrix but modified as decribed
def reorder_matrix_2(source_v, target_v, source_matrix, target_matrix):

    target_indices  = []
    source_indices  = []
    for i, item in enumerate (source_v):
        if(item.startswith("PF")):
            target_index = np.where(target_v == item)[0]
            #print(f"target index for {item}: {target_index}")
            # if the source is in the target
            if(target_index.size !=0):
                target_indices.append(target_index[0])
                source_indices.append(i)
        else:
            continue

    #print('indices needed in target matrix and in new order', target_indices)
    #print('indices needed in source vector', source_indices)

    # reorder the matrix
    reordered_t_matrix = target_matrix[target_indices, :]
    reordered_t_matrix = reordered_t_matrix[:, target_indices]
    
    reordered_s_matrix = source_matrix[source_indices, :]
    reordered_s_matrix = reordered_s_matrix[:, source_indices]
    
    reduced_source_v  = source_v[source_indices]
    
    return reordered_s_matrix, reordered_t_matrix

'''



#
# performs mantel test on 2 matrices - in this case two matrices from word2vec
#
def custom_mantel_test(source_matrix, target_matrix, permutations=10):
    
    s = time.time()

    
    # Ensure that the matrices are square and of the same size
    assert source_matrix.shape == target_matrix.shape, "Matrices must have the same shape."
    assert source_matrix.shape[0] == source_matrix.shape[1], "Matrices must be square."
    assert target_matrix.shape[0] == target_matrix.shape[1], "Matrices must be square."

    # Flatten the upper triangular parts of the matrices
    print("flattening matrices......")
    triu_indices = np.triu_indices_from(source_matrix, k=1)
    distances1 = source_matrix[triu_indices]
    distances2 = target_matrix[triu_indices]

    print("calculating pearson correlation....")
    # Calculate the observed Pearson correlation
    observed_corr, _ = pearsonr(distances1, distances2)

    print("running permutation tests....")
    # Permutation test
    permuted_corrs = []
    i = 0
    for _ in range(permutations):
        np.random.shuffle(distances2)
        permuted_corr, _ = pearsonr(distances1, distances2)
        permuted_corrs.append(permuted_corr)
        print(f" - permutation {i} complete")
        i+=1

    # Calculate p-value
    print("- calculating p-value....")
    permuted_corrs = np.array(permuted_corrs)
    p_value = np.mean(permuted_corrs >= observed_corr)
    
    e = time.time()
    
    #print(f"- test complete in {round(e-s,2)}s. correlation: {observed_corr}. p-value: {p_value}")

    return observed_corr, p_value

<>:58: SyntaxWarning: invalid escape sequence '\|'
<>:58: SyntaxWarning: invalid escape sequence '\|'
/var/folders/kp/bqnb4b7n4ng50xtbznpbx7xh0000gn/T/ipykernel_29191/3132118102.py:58: SyntaxWarning: invalid escape sequence '\|'
  pfam_search  = re.search("\|(PF.*)", item)


##### Test reorder

In [168]:

source_vector = np.array(['d', 'b', 'f'])
target_vector = np.array(['a', 'b', 'c', 'd'])

print(f"source vector: {source_vector}\ntarget vector: {target_vector}\n")
print(f"original target matrix: \n{target_matrix}\n")

target_matrix = np.array([  [10, 11, 12, 13],
                            [20, 21, 22, 23],
                            [30, 31, 32, 33],
                            [40, 41, 42, 43]])

#
# -------- calll routine
#
# found_items, missing_items, reordered_vector, reordered_matrix
found_items, missing_items, reduced_target_vector, reduced_target_matrix = reduce_matrix(source_vector, target_vector, target_matrix)

print('------------------- result -----------------\n')
print(f"missing items (in source, not in target): \n{missing_items}")
print(f"found items: \n{found_items}")
print(f"reduced target vector: \n{reduced_target_vector}")
print(f"reduced target matrix: \n{reduced_target_matrix}")

source vector: ['d' 'b' 'f']
target vector: ['a' 'b' 'c' 'd']

original target matrix: 
[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]

------------------- result -----------------

missing items (in source, not in target): 
['f']
found items: 
['d', 'b']
reduced target vector: 
['d' 'b']
reduced target matrix: 
[[43 41]
 [23 21]]


#### Test extracting pfam ids from evo vector

In [169]:
evo_distance_file = '/Users/patrick/dev/ucl/word2vec/COMP_0158_MSC_PROJECT/data/models/evo/rand_rep_distance_matrix.npy'

evo_vector, evo_matrix = extract_matrix_vector_files(evo_distance_file)

evo_pfam_ids = extract_evo_pfam_ids(evo_vector)

print(evo_pfam_ids)


['PF10417', 'PF21734', 'PF21578', 'PF12574', 'PF09847', 'PF00244', 'PF16998', 'PF00389', 'PF02826', 'PF00198', 'PF16078', 'PF04029', 'PF04463', 'PF16620', 'PF05635', 'PF20758', 'PF08521', 'PF08793', 'PF20150', 'PF11591', 'PF01257', 'PF08975', 'PF03390', 'PF21584', 'PF03171', 'PF13532', 'PF13640', 'PF13661', 'PF13759', 'PF20515', 'PF10014', 'PF13239', 'PF13563', 'PF06983', 'PF06052', 'PF12578', 'PF17644', 'PF11330', 'PF00803', 'PF01073', 'PF06725', 'PF02829', 'PF10605', 'PF00725', 'PF02737', 'PF18321', 'PF06439', 'PF16121', 'PF16122', 'PF17947', 'PF03061', 'PF13279', 'PF13622', 'PF20789', 'PF12729', 'PF04476', 'PF18671', 'PF17837', 'PF05902', 'PF01812', 'PF06189', 'PF09038', 'PF21432', 'PF03491', 'PF07694', 'PF01367', 'PF02739', 'PF05761', 'PF02872', 'PF02096', 'PF01591', 'PF00393', 'PF02294', 'PF07698', 'PF07696', 'PF07695', 'PF07697', 'PF00001', 'PF00002', 'PF00003', 'PF13853', 'PF02949', 'PF08395', 'PF02117', 'PF10292', 'PF02175', 'PF10316', 'PF10317', 'PF10318', 'PF10327', 'PF10319'

In [73]:

# load movel and vector of pfam words
model = Word2Vec.load("/Users/patrick/dev/ucl/word2vec/comp_0158_msc_project/data/models/hpc/mac/w2v_20240831_sg1_mc1_w3_v5_mac.model")
npy_distance_file = '/Users/patrick/dev/ucl/word2vec/comp_0158_msc_project/data/models/hpc/mac/w2v_20240831_sg1_mc1_w3_v5.model_dist_normalised_mac.npy'

# load the pre-calculated distance matrix and vectors
vocab_vector, w2v_dist_matrix =  extract_matrix_vector_files(npy_distance_file)

# Size of the vocabulary
vocab_size = len(model.wv.key_to_index)

# Get the vector rep of 2 pfam ids from a model
pfam_1 = 'PF00469'
pfam_2 = 'PF03945'
gap = 'GAP'

# ---------------------------------------------------------------------
# Calculate distances directly by retriveing model encoding
# ---------------------------------------------------------------------
print('\ncalculating distance from scratch....')
vector_1 = model.wv[pfam_1]
vector_2 = model.wv[pfam_2]

# calculate distance
distance = np.linalg.norm(vector_1 - vector_2)

print(f"{pfam_1} : {vector_1} \n{pfam_2} : {vector_2}\nEuclidean distance: {distance}")

# ---------------------------------------------------------------------
# Retrieve pre-calculated distances for the same words
# ---------------------------------------------------------------------
print('\nretrieving pre-calculated distaances....')
# find the indices in the vocab vector
index_0 = get_word_index(gap, vocab_vector)
index_1 = get_word_index(pfam_1, vocab_vector)
index_2 = get_word_index(pfam_2, vocab_vector)

print(vocab_vector[index_1])
print(vocab_vector[index_2])

# now check that the distance is the same
print(f"found {pfam_1} at {index_1} and {pfam_2} at {index_2}")
print(f"distance diag: {w2v_dist_matrix[index_2, index_2]}")

# note because its diagonal..... rows are filled first, so if index 2 is greater than index 1 you need to reverse
print(f"normalised distance: {w2v_dist_matrix[index_1, index_2]}")
print(f"normalised distance: {w2v_dist_matrix[index_2, index_1]}")


# ---------------------------------------------------------------------
# Make w2v matrix symmetrical
# ---------------------------------------------------------------------

#
# Make it symmetrical
#
print('\ncreating symmetric matrix....')
s = time.time()
w2v_dist_matrix_sym = make_symmetrical(w2v_dist_matrix)
e = time.time()

print(f"symmetric matrix created in {round(e-s,2)}s")
print(f"distance diag: {w2v_dist_matrix_sym[index_2, index_2]}")

# note because its diagonal..... rows are filled first, so if index 2 is greater than index 1 you need to reverse
print(f"normalised distance: {w2v_dist_matrix_sym[index_1, index_2]}")
print(f"normalised distance: {w2v_dist_matrix_sym[index_2, index_1]}")

# ---------------------------------------------------------------------
# Test symmetric
# ---------------------------------------------------------------------
'''
print('\ntesting that matrix is symmetric....')
test_symmetric(w2v_dist_matrix_sym)
print('\ntest complete....')
'''


calculating distance from scratch....
PF00469 : [ 0.08747003 -0.05775652  0.17974336  0.19409668  0.18597658] 
PF03945 : [ 0.68811744 -0.7162888   1.8892967   0.36172312 -1.4784527 ]
Euclidean distance: 2.5525355339050293

retrieving pre-calculated distaances....
PF00469
PF03945
found PF00469 at 14218 and PF03945 at 9275
distance diag: 0.0
normalised distance: 0.0
normalised distance: 0.10943721839576377

creating symmetric matrix....
symmetric matrix created in 8.53s
distance diag: 0.0
normalised distance: 0.10943721839576377
normalised distance: 0.10943721839576377


"\nprint('\ntesting that matrix is symmetric....')\ntest_symmetric(w2v_dist_matrix_sym)\nprint('\ntest complete....')\n"

## COMPARE DISTANCES

##### Extract matrices and vectors and prepare for comparison

In [129]:
# evolutionary distance matrix (matrix and vector)
#evo_distance_file = '/Users/patrick/dev/ucl/word2vec/COMP_0158_MSC_PROJECT/data/models/evo/rand_rep_distance_matrix_small.npy'
evo_distance_file = '/Users/patrick/dev/ucl/word2vec/COMP_0158_MSC_PROJECT/data/models/evo/rand_rep_distance_matrix.npy'

# w2v distance matrix (matrix and vector)
w2v_distance_file = '/Users/patrick/dev/ucl/word2vec/comp_0158_msc_project/data/models/hpc/mac/w2v_20240831_sg1_mc1_w3_v5.model_dist_normalised_mac.npy'

# extract files
print('extracting matrices and vectors from .npy files')
s = time.time()
evo_vector, evo_matrix = extract_matrix_vector_files(evo_distance_file)
w2v_vector, w2v_matrix = extract_matrix_vector_files(w2v_distance_file)
e = time.time()
print(f"extracting files. time taken: {round(e-s,2)}s\n")


# need  to make w2v matrix symmetrical and convert array into numpy array
print('making w2v distance matrix symmetrical')
s = time.time()
w2v_matrix_sym = make_symmetrical(w2v_matrix)
e = time.time()
print(f"make w2v symmetrical. time taken: {round(e-s,2)}s\n")

# need to also extract pfam ids from the evo vector and convert to numpy array
print('extracting pfam ids from evo vector into new np array')
s = time.time()
evo_pfam_ids  = extract_evo_pfam_ids(evo_vector)
evo_vector_np = np.array(evo_pfam_ids)
e = time.time()
print(f"extraction complete. time taken: {round(e-s,2)}s\n")

# also convert w2v vector to numpy array
w2v_vector_np = np.array(w2v_vector)

print(f"word2vec vector length: {len(w2v_vector)}")
print(f"word2vec vector (np) length: {w2v_vector_np.size}\n")

print(f"word2vec dist matrix shape: {w2v_matrix.shape}")
print(f"word2vec dist sym matrix shape: {w2v_matrix_sym.shape}\n")

print(f"evo vector (np) length: {evo_vector_np.size}")
print(f"evo dist matrix shape: {evo_matrix.shape}")


extracting matrices and vectors from .npy files
extracting files. time taken: 6.83s

making w2v distance matrix symmetrical
make w2v symmetrical. time taken: 8.09s

extracting pfam ids from evo vector into new np array
extraction complete. time taken: 0.1s

word2vec vector length: 15473
word2vec vector (np) length: 15473

word2vec dist matrix shape: (15473, 15473)
word2vec dist sym matrix shape: (15473, 15473)

evo vector (np) length: 20651
evo dist matrix shape: (20651, 20651)


### Reorder matrices

In [190]:
#reordered_s_matrix, reordered_t_matrix = reorder_matrix_2(w2v_vector_np, evo_vector, w2v_dist_matrix_sym, evo_matrix)

print(f"source matrix shape: {w2v_dist_matrix_sym.shape} vocab: {len(w2v_vector_np)}")
print(f"target matrix shape: {evo_matrix.shape} vocab: {len(evo_vector)}\n")

# reorder matrices
#source_matrix, target_matrix = reorder_matrix_2(w2v_vector_np, evo_vector, w2v_dist_matrix, evo_matrix)
print('reducing evo matrix....')
s = time.time()
#found_items, missing_items, reordered_vector, reordered_matrix
found_items, missing_items, reduced_evo_vector, reduced_evo_matrix = reduce_matrix(w2v_vector_np, evo_vector_np, evo_matrix)
e = time.time()
print(f"reduce evo matrix. time taken: {round(e-s,2)}s\n")

print(f"found items length: {len(found_items)}.")
print(f"missing items length: {len(missing_items)}.\n")

print(f"reordered target vector length: {reduced_evo_vector.size}.")
print(f"reordered target matrix shape: {reduced_evo_matrix.shape}.")
print(f"source matrix shape: {w2v_dist_matrix_sym.shape}.")

# missing items are still in the source vector and matrix so need to remove them as well
print('\nreducing w2v matrix....')
s = time.time()
w2v_common_vector_np = np.array(found_items)
found_items, missing_items, w2v_common_vector, w2v_common_matrix = reduce_matrix(w2v_common_vector_np, w2v_vector_np, w2v_dist_matrix_sym)
e = time.time()
print(f"reduce w2v matrix. time taken: {round(e-s,2)}s\n")

print(f"found items length: {len(found_items)}.")
print(f"missing items length: {len(missing_items)}.\n")

print(f"reordered w2v vector length: {w2v_common_vector.size}.")
print(f"reordered w2v matrix shape: {w2v_common_matrix.shape}.")


# Ensure that the matrices are square and of the same size
assert w2v_common_matrix.shape == reduced_evo_matrix.shape, "Both matrices must have the same shape."
assert w2v_common_matrix.shape[0] == w2v_common_matrix.shape[1], "Word2Vec matrix must be square."
assert reduced_evo_matrix.shape[0] == reduced_evo_matrix.shape[1], "Evo matrix must be square."

source matrix shape: (15473, 15473) vocab: 15473
target matrix shape: (20651, 20651) vocab: 20651

reducing evo matrix....
reduce evo matrix. time taken: 29.34s

found items length: 15030.
missing items length: 439.

reordered target vector length: 15030.
reordered target matrix shape: (15030, 15030).
source matrix shape: (15473, 15473).

reducing w2v matrix....
reduce w2v matrix. time taken: 21.16s

found items length: 15030.
missing items length: 0.

reordered w2v vector length: 15030.
reordered w2v matrix shape: (15030, 15030).


#### Mantel test - custom

In [ ]:
#
# run a mantel test
#
s = time.time()
num_permutations = 50
observed_corr, p_value = custom_mantel_test(w2v_common_matrix, reduced_evo_matrix, num_permutations )
e = time.time()
print(f"Mantel test with {num_permutations} complete in {round(e-s,2)}s corr : {observed_corr} p_val : {p_value}.")

s = time.time()
num_permutations = 100
observed_corr, p_value = custom_mantel_test(w2v_common_matrix, reduced_evo_matrix, num_permutations )
e = time.time()
print(f"Mantel test with {num_permutations} complete in {round(e-s,2)}s corr : {observed_corr} p_val : {p_value}.")

### Mantel test - scikitbio

In [185]:
num_permutations = [25,50,100]

for n in num_permutations:
    print(f"Starting Mantel test with {n} permutations")
    s= time.time()
    corr_coeff, p_value, num = mantel(w2v_common_matrix, reduced_evo_matrix, permutations=n)
    print (corr_coeff, p_value, num)
    e = time.time()
    print(f"Mantel test with {n} permutations complete in {round(e-s,2)}s corr : {corr_coeff} p_val : {p_value} num: {num}.")


Starting Mantel test with 25 permutations
0.03983702074381344 0.038461538461538464 15030
Mantel test with 25 permutations complete in 38.32s corr : 0.03983702074381344 p_val : 0.038461538461538464 num: 15030.
Starting Mantel test with 50 permutations
0.03983702074381344 0.0196078431372549 15030
Mantel test with 50 permutations complete in 45.48s corr : 0.03983702074381344 p_val : 0.0196078431372549 num: 15030.
Starting Mantel test with 100 permutations
0.03983702074381344 0.009900990099009901 15030
Mantel test with 100 permutations complete in 56.14s corr : 0.03983702074381344 p_val : 0.009900990099009901 num: 15030.


In [192]:
w2v_dist_matrix = DistanceMatrix(w2v_common_matrix, ids=w2v_common_vector)
evo_dist_matrix = DistanceMatrix(reduced_evo_matrix, ids=reduced_evo_vector)

num_permutations = [25,50,100]

for n in num_permutations:
    print(f"Starting Mantel test with {n} permutations")
    s= time.time()
    corr_coeff, p_value, num = mantel(w2v_dist_matrix, evo_dist_matrix, permutations=n)
    e = time.time()
    print(f"Mantel test with {n} permutations complete in {round(e-s,2)}s corr : {corr_coeff} p_val : {p_value} num: {num}.\n")

Starting Mantel test with 25 permutations
Mantel test with 25 permutations complete in 28.8s corr : 0.03983702074381344 p_val : 0.038461538461538464 num: 15030.

Starting Mantel test with 50 permutations
Mantel test with 50 permutations complete in 31.01s corr : 0.03983702074381344 p_val : 0.0196078431372549 num: 15030.

Starting Mantel test with 100 permutations
Mantel test with 100 permutations complete in 46.93s corr : 0.03983702074381344 p_val : 0.009900990099009901 num: 15030.



## COSINE DISTANCES

In [237]:
from sklearn.metrics.pairwise import cosine_distances
from sklearn.metrics.pairwise import euclidean_distances

#
# gets the vocab for a model - returns a python list and a numpy array
#
def get_model_vocab(model_dir, model_name):
    pfam_ids = []

    model = Word2Vec.load(model_dir+model_name+'.model')
    vocab = model.wv.key_to_index
    
    print(f"Model {model_name} has a vocab of {len(vocab)}")
    for word in vocab:
        pfam_ids.append(word)
    return pfam_ids

# creates a distance matrix for a model
# this assumes a certain naming convention for models and vocab files
# For example
#   If the model name is : w2v_20240811_v5_w5_mc3, the code will expect
#   - a model called w2v_20240811_v5_w5_mc3.model
#   - a vocab file  called w2v_20240811_v5_w5_mc3.txt
#   And will output a distance matrix called:
#   - w2v_20240811_v5_w5_mc3_dist.npy
#   
def create_cosine_distance_matrix(model_base_name, model_name):
    print(f"Creating distance matrix for model {model_base_name}")
    print(f"Loading model {model_name}")
    # get pfam ids from the vocab file corresponding to the model
    model       = Word2Vec.load(model_name)
    
    #print('model_vocab:', model.wv.key_to_index)
    pfam_ids = []
    vocab = model.wv.key_to_index
    
    print(f"Model {model_base_name} has a vocab of {len(vocab)}")
    
    word_vectors    = model.wv

    print('word vectors shape:', word_vectors.vectors.shape)
    #print(word_vectors[0].shape)
    
    '''
    for word in vocab:
        pfam_ids.append(word)
    num_entries     = len(pfam_ids)
    
    error_count = 0
    success_count = 0
    s = time.time()
    vectors = np.empty(num_entries)
    
    # loop through each entry and calulate its distance
    for i in range(num_entries):
        pfam_1 = pfam_ids[i]
        try:
            v1 = model.wv[pfam_1]
            vectors[i] = v1
            success_count +=1
        except Exception as e: # a bit convoluted, but want to print out the missing pfam
            print('Exception', e)
            continue
    '''
    s = time.time()
    print('calculating cosine distances')
    cosine_distance_matrix = cosine_distances(word_vectors.vectors, word_vectors.vectors)
    
    print('calculating euclidean distances')
    euclidean_distance_matrix = euclidean_distances(word_vectors.vectors, word_vectors.vectors)
    
    #normalized_dist_matrix = (distance_matrix - min_dist) / (max_dist - min_dist)
    # save distance matrix and pfam ids
    #output_name = model_name+"_cosine_dist_normalised.npy"
    #with open(output_name, "wb") as f:
    #    np.save(f, cosine_distance_matrix)
    #    np.save(f, pfam_ids)

    e = time.time()
    print(f"cosine distance matrix computed for model: {model_base_name}. num words: {num_entries}. time: {round(e-s,2)}s.")
    
    return euclidean_distance_matrix, cosine_distance_matrix

In [238]:
output_dir = '/Users/patrick/dev/ucl/word2vec/comp_0158_msc_project/data/models/hpc/mac/'
model_base_name = 'w2v_20240831_sg1_mc1_w3_v5_mac.model'
model_name      = output_dir+model_base_name

print(f"loading model {model_name}.")
        
#
#--------------------------- create dist -----------------------
#
s=time.time()
print("creating distance matrix")
euclidean_distance_matrix, cosine_distance_matrix = create_cosine_distance_matrix(model_base_name, model_name)
e = time.time()
matrix_time_taken=str(round(e-s, 2))

loading model /Users/patrick/dev/ucl/word2vec/comp_0158_msc_project/data/models/hpc/mac/w2v_20240831_sg1_mc1_w3_v5_mac.model.
creating distance matrix
Creating distance matrix for model w2v_20240831_sg1_mc1_w3_v5_mac.model
Loading model /Users/patrick/dev/ucl/word2vec/comp_0158_msc_project/data/models/hpc/mac/w2v_20240831_sg1_mc1_w3_v5_mac.model
Model w2v_20240831_sg1_mc1_w3_v5_mac.model has a vocab of 15473
word vectors shape: (15473, 5)
calculating cosine distances
calculating euclidean distances
cosine distance matrix computed for model: w2v_20240831_sg1_mc1_w3_v5_mac.model. num words: 5. time: 6.31s.


In [273]:
from scipy.spatial.distance import cosine

# load model and vocab
model   = Word2Vec.load(model_name)
vocab   = model.wv.key_to_index

# list all items in vocab

for i, word_1 in enumerate(vocab):
    for j, word_2 in enumerate(vocab):
        
        if(word_1 == 'GAP' or word_1 == 'DISORDER' or word_1 == 'START_GAP' or word_1 == 'STOP_GAP'):
            continue
        if(word_2 == 'GAP' or word_2 == 'DISORDER' or word_2 == 'START_GAP' or word_2 == 'STOP_GAP'):
            continue
        if(word_1 == word_2):
            continue
        
        #print(i, word)
        v1 = model.wv[word_1]
        v2 = model.wv[word_2]

        euc_dist = np.linalg.norm(v1 - v2)
        d2       = euclidean_distance_matrix[i,j]
        d3       = euclidean_distance_matrix[j,i]
        
        # work out cosine myself
        cosine_similarity = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
        cos_dist = 1 - cosine_similarity
        
        # get from library
        cos_dist_1 = cosine(v1, v2)
        
        # get from matrix
        d4       = cosine_distance_matrix[i,j]
        d5       = cosine_distance_matrix[j,i]
        
        print(f"EUC: {word_1} to {word_2} : \t| {euc_dist} \t| {d2}  \t| {d3}")
        print(f"COS: {word_1} to {word_2} : \t| {cos_dist_1} \t| {d4}  \t| {d5}\n")

            
        assert np.round(euc_dist, 4)     == np.round(d2, 4), "Euclidean distance not the same - d2"
        assert np.round(euc_dist, 4)     == np.round(d3, 4), "Euclidean distance not the same - d3"
        assert np.round(cos_dist_1, 2)   == np.round(d4, 2), f"Cos distance not the same - {cos_dist_1} v {d4}."
        assert np.round(cos_dist_1, 2)   == np.round(d5, 2), "Cos distance not the same - d5."
        


EUC: PF00096 to PF00400 : 	| 5.734714031219482 	| 5.734714031219482  	| 5.734714031219482
COS: PF00096 to PF00400 : 	| 0.5739585541465781 	| 0.5739585161209106  	| 0.5739585161209106



AssertionError: Cos distance not the same - 0.5739585541465781 v 0.5739585161209106.